apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: relieflink

bases:
  - ../../base

configMapGenerator:
  - name: relieflink-config
    behavior: merge
    literals:
      - LOG_LEVEL=warn
      - ENVIRONMENT=production

commonLabels:
  environment: production
