apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: relieflink

resources:
  - namespace.yaml
  - storageclass.yaml
  - secrets-configmap.yaml
  - postgres.yaml
  - redis.yaml
  - config-service.yaml
  - api-gateway.yaml
  - web-service.yaml
  - auth-service.yaml
  - request-service.yaml
  - volunteer-service.yaml
  - notification-service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: relieflink
  app.kubernetes.io/version: "1.0.0"
  environment: production
