apiVersion: v1
kind: ConfigMap
metadata:
  name: relieflink-config
  namespace: relieflink
data:
  NODE_ENV: "production"
  LOG_LEVEL: "info"
  AUTH_SERVICE_URL: "http://auth-service:3001"
  REQUEST_SERVICE_URL: "http://request-service:3004"
  VOLUNTEER_SERVICE_URL: "http://volunteer-service:3003"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3002"
  CONFIG_SERVICE_URL: "http://config-service:3006"
  API_GATEWAY_URL: "http://api-gateway:3005"
  NEXT_PUBLIC_API_BASE_URL: "/api"
  WEB_PUBLIC_ORIGIN: "*"
